
package main;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    

    private int mouseX, mouseY;
    
    public MainScreen() {
        initComponents();
        setSize(875, 550);
        setLocationRelativeTo(null);
        
        //minimizar.setIcon(new ImageIcon(new ImageIcon("src/img/minPink.png").getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT)));
        //cerrar.setIcon(new ImageIcon(new ImageIcon("src/img/close.png").getImage().getScaledInstance(16, 16, Image.SCALE_DEFAULT)));

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        PanelPrincipal = new javax.swing.JPanel();
        addCLabel = new javax.swing.JLabel();
        findCLabel = new javax.swing.JLabel();
        findPLabel = new javax.swing.JLabel();
        listPLabel = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        WorkPanel = new javax.swing.JPanel();
        txtTelefono = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtDNI = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        txtDomicilio = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        searchClient = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        searchNumbers = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        listClients = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        minimizar = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(875, 560));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(875, 560));
        setResizable(false);
        setSize(new java.awt.Dimension(875, 560));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(44, 44, 44));
        background.setMinimumSize(new java.awt.Dimension(875, 550));
        background.setPreferredSize(new java.awt.Dimension(875, 550));
        background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backgroundMouseDragged(evt);
            }
        });
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backgroundMousePressed(evt);
            }
        });
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelPrincipal.setBackground(new java.awt.Color(51, 54, 61));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addCLabel.setBackground(new java.awt.Color(102, 102, 102));
        addCLabel.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        addCLabel.setForeground(new java.awt.Color(255, 255, 255));
        addCLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addCLabel.setText("Agregar clientes");
        addCLabel.setOpaque(true);
        addCLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addCLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addCLabelMouseExited(evt);
            }
        });
        PanelPrincipal.add(addCLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 180, 220, 40));

        findCLabel.setBackground(new java.awt.Color(102, 102, 102));
        findCLabel.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        findCLabel.setForeground(new java.awt.Color(255, 255, 255));
        findCLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        findCLabel.setText("Buscar cliente");
        findCLabel.setOpaque(true);
        findCLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findCLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                findCLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                findCLabelMouseExited(evt);
            }
        });
        PanelPrincipal.add(findCLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 230, 220, 40));

        findPLabel.setBackground(new java.awt.Color(102, 102, 102));
        findPLabel.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        findPLabel.setForeground(new java.awt.Color(255, 255, 255));
        findPLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        findPLabel.setText("Buscar Telefonos");
        findPLabel.setOpaque(true);
        findPLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findPLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                findPLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                findPLabelMouseExited(evt);
            }
        });
        PanelPrincipal.add(findPLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 280, 220, 40));

        listPLabel.setBackground(new java.awt.Color(102, 102, 102));
        listPLabel.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        listPLabel.setForeground(new java.awt.Color(255, 255, 255));
        listPLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listPLabel.setText("Listar clientes de una ciudad");
        listPLabel.setOpaque(true);
        listPLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listPLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listPLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                listPLabelMouseExited(evt);
            }
        });
        PanelPrincipal.add(listPLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 330, 220, 40));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/contact.png"))); // NOI18N
        PanelPrincipal.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 50, 100, 100));

        background.add(PanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 35, 250, 500));

        WorkPanel.setLayout(null);

        txtTelefono.setBackground(new java.awt.Color(51, 54, 61));
        txtTelefono.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DNI");
        txtTelefono.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre");
        txtTelefono.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Apellido");
        txtTelefono.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ciudad");
        txtTelefono.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Domicilio");
        txtTelefono.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Telefono");
        txtTelefono.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jButton1.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        txtTelefono.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 125, 30));

        txtDNI.setText("jTextField1");
        txtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIActionPerformed(evt);
            }
        });
        txtTelefono.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 85, 200, 30));

        txtNombre.setText("jTextField1");
        txtTelefono.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 135, 250, 30));

        txtApellido.setText("jTextField2");
        txtTelefono.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 185, 250, 30));

        txtCiudad.setText("jTextField3");
        txtTelefono.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 235, 250, 30));

        txtDomicilio.setText("jTextField4");
        txtTelefono.add(txtDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 285, 250, 30));

        jTextField5.setText("jTextField5");
        txtTelefono.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 335, 250, 30));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agregar nuevos Clientes");
        txtTelefono.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 30, -1, -1));

        jButton2.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        txtTelefono.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 400, 125, 30));

        WorkPanel.add(txtTelefono);
        txtTelefono.setBounds(0, 0, 550, 500);

        searchClient.setBackground(new java.awt.Color(51, 54, 61));

        jLabel2.setText("search client");

        javax.swing.GroupLayout searchClientLayout = new javax.swing.GroupLayout(searchClient);
        searchClient.setLayout(searchClientLayout);
        searchClientLayout.setHorizontalGroup(
            searchClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchClientLayout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel2)
                .addContainerGap(264, Short.MAX_VALUE))
        );
        searchClientLayout.setVerticalGroup(
            searchClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchClientLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel2)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        WorkPanel.add(searchClient);
        searchClient.setBounds(0, 0, 550, 500);

        searchNumbers.setBackground(new java.awt.Color(51, 54, 61));

        jLabel3.setText("Search phones opcion 3");

        javax.swing.GroupLayout searchNumbersLayout = new javax.swing.GroupLayout(searchNumbers);
        searchNumbers.setLayout(searchNumbersLayout);
        searchNumbersLayout.setHorizontalGroup(
            searchNumbersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchNumbersLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jLabel3)
                .addContainerGap(218, Short.MAX_VALUE))
        );
        searchNumbersLayout.setVerticalGroup(
            searchNumbersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchNumbersLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel3)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        WorkPanel.add(searchNumbers);
        searchNumbers.setBounds(0, 0, 550, 500);

        listClients.setBackground(new java.awt.Color(51, 54, 61));

        jLabel4.setText("opcion 4");

        javax.swing.GroupLayout listClientsLayout = new javax.swing.GroupLayout(listClients);
        listClients.setLayout(listClientsLayout);
        listClientsLayout.setHorizontalGroup(
            listClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listClientsLayout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(252, 252, 252))
        );
        listClientsLayout.setVerticalGroup(
            listClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listClientsLayout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel4)
                .addContainerGap(259, Short.MAX_VALUE))
        );

        WorkPanel.add(listClients);
        listClients.setBounds(0, 0, 550, 500);

        background.add(WorkPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 35, 550, 500));

        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minPink.png"))); // NOI18N
        minimizar.setAlignmentY(0.0F);
        minimizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        minimizar.setPreferredSize(new java.awt.Dimension(26, 26));
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        background.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 26, 26));
        minimizar.getAccessibleContext().setAccessibleName("");

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        cerrar.setMaximumSize(new java.awt.Dimension(26, 26));
        cerrar.setMinimumSize(new java.awt.Dimension(26, 26));
        cerrar.setPreferredSize(new java.awt.Dimension(26, 26));
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        background.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 26, 26));

        titulo.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Libreta de contactos");
        background.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 10, -1, -1));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 875, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCLabelMouseClicked
        txtTelefono.setVisible(true);
        searchClient.setVisible(false);
        searchNumbers.setVisible(false);
        listClients.setVisible(false);
        //addDeleteClient.setBackground(Color.red);
        
    }//GEN-LAST:event_addCLabelMouseClicked

    private void findCLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findCLabelMouseClicked
        txtTelefono.setVisible(false);
        searchClient.setVisible(true);
        searchNumbers.setVisible(false);
        listClients.setVisible(false);
    }//GEN-LAST:event_findCLabelMouseClicked

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        dispose();
    }//GEN-LAST:event_cerrarMouseClicked

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizarMouseClicked


    private void backgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMousePressed
        mouseX=evt.getX();
        mouseY=evt.getY();
    }//GEN-LAST:event_backgroundMousePressed

    private void backgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseDragged
        setLocation(this.getLocation().x+evt.getX()-mouseX,this.getLocation().y+evt.getY()-mouseY);
    }//GEN-LAST:event_backgroundMouseDragged

    private void addCLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCLabelMouseEntered
        addCLabel.setBackground(Color.red);
    }//GEN-LAST:event_addCLabelMouseEntered

    private void addCLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCLabelMouseExited
        addCLabel.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_addCLabelMouseExited

    private void findCLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findCLabelMouseEntered
        findCLabel.setBackground(Color.red);
    }//GEN-LAST:event_findCLabelMouseEntered

    private void findCLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findCLabelMouseExited
        findCLabel.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_findCLabelMouseExited

    private void findPLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findPLabelMouseEntered
        findPLabel.setBackground(Color.red);
    }//GEN-LAST:event_findPLabelMouseEntered

    private void findPLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findPLabelMouseExited
        findPLabel.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_findPLabelMouseExited

    private void listPLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listPLabelMouseEntered
        listPLabel.setBackground(Color.red);
    }//GEN-LAST:event_listPLabelMouseEntered

    private void listPLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listPLabelMouseExited
        listPLabel.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_listPLabelMouseExited

    private void findPLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findPLabelMouseClicked
        txtTelefono.setVisible(false);
        searchClient.setVisible(false);
        searchNumbers.setVisible(true);
        listClients.setVisible(false);
    }//GEN-LAST:event_findPLabelMouseClicked

    private void listPLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listPLabelMouseClicked
        txtTelefono.setVisible(false);
        searchClient.setVisible(false);
        searchNumbers.setVisible(false);
        listClients.setVisible(true);
    }//GEN-LAST:event_listPLabelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel WorkPanel;
    private javax.swing.JLabel addCLabel;
    private javax.swing.JPanel background;
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel findCLabel;
    private javax.swing.JLabel findPLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPanel listClients;
    private javax.swing.JLabel listPLabel;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel minimizar;
    private javax.swing.JPanel searchClient;
    private javax.swing.JPanel searchNumbers;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPanel txtTelefono;
    // End of variables declaration//GEN-END:variables
}
